"""
WARNING: code generated by the awsv plugin manager, this code
         should not be edited manually.
"""
def example_method(**kwargs):

    # Write your method code here
    # A 'kwargs' dict is available with these entries:
    # kwargs["path"] => local file path
    # kwargs["cloud_path"] => file path on the cloud
    # kwargs["local_root"] => the current project's root folder

    file_path = kwargs["path"]